In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2026-06-04 17:09:07.264337: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-04 17:09:07.415806: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-04 17:09:07.415843: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-04 17:09:07.430685: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-04 17:09:07.459208: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-04 17:09:07.459893: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### One Hot Representation Based on predefined Vocabulary size

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5025, 5994, 6982, 4198],
 [5025, 5994, 6982, 3730],
 [5025, 2097, 6982, 2829],
 [8332, 8235, 2392, 549, 3919],
 [8332, 8235, 2392, 549, 1885],
 [4727, 5025, 1144, 6982, 9040],
 [664, 6278, 2044, 549]]

## word Embedding Representation

In [8]:


from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

### Sequence Padding as Neural networks expect inputs of a fixed size,

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5025 5994 6982 4198]
 [   0    0    0    0 5025 5994 6982 3730]
 [   0    0    0    0 5025 2097 6982 2829]
 [   0    0    0 8332 8235 2392  549 3919]
 [   0    0    0 8332 8235 2392  549 1885]
 [   0    0    0 4727 5025 1144 6982 9040]
 [   0    0    0    0  664 6278 2044  549]]


## feature representation

In [ ]:

dim=10

### Building the Embedding Layer key parameters:-Vocabulary size , Feature Dimension, Input_Length

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Vector Transformation :-  Transform the padded indices into dense vectors

In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 77ms/step


array([[[ 0.02419548,  0.02284564, -0.01140075,  0.00815455,
         -0.04470843, -0.02690262, -0.02221215,  0.04440018,
          0.02344405, -0.02898219],
        [ 0.02419548,  0.02284564, -0.01140075,  0.00815455,
         -0.04470843, -0.02690262, -0.02221215,  0.04440018,
          0.02344405, -0.02898219],
        [ 0.02419548,  0.02284564, -0.01140075,  0.00815455,
         -0.04470843, -0.02690262, -0.02221215,  0.04440018,
          0.02344405, -0.02898219],
        [ 0.02419548,  0.02284564, -0.01140075,  0.00815455,
         -0.04470843, -0.02690262, -0.02221215,  0.04440018,
          0.02344405, -0.02898219],
        [ 0.04427935, -0.01936251, -0.03635266,  0.04244074,
         -0.01353799, -0.03765942, -0.04916368,  0.04445559,
          0.01669676, -0.01556396],
        [ 0.04384034, -0.01403742, -0.00416575, -0.00857059,
         -0.00630454, -0.03281386, -0.01693771,  0.02295699,
         -0.0383137 ,  0.0062729 ],
        [-0.03078157,  0.01142633,  0.0488565 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5025, 5994, 6982, 4198], dtype=int32)

### View the 10-dimensional vector representation of the first sentence

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[ 0.02419548,  0.02284564, -0.01140075,  0.00815455, -0.04470843,
        -0.02690262, -0.02221215,  0.04440018,  0.02344405, -0.02898219],
       [ 0.02419548,  0.02284564, -0.01140075,  0.00815455, -0.04470843,
        -0.02690262, -0.02221215,  0.04440018,  0.02344405, -0.02898219],
       [ 0.02419548,  0.02284564, -0.01140075,  0.00815455, -0.04470843,
        -0.02690262, -0.02221215,  0.04440018,  0.02344405, -0.02898219],
       [ 0.02419548,  0.02284564, -0.01140075,  0.00815455, -0.04470843,
        -0.02690262, -0.02221215,  0.04440018,  0.02344405, -0.02898219],
       [ 0.04427935, -0.01936251, -0.03635266,  0.04244074, -0.01353799,
        -0.03765942, -0.04916368,  0.04445559,  0.01669676, -0.01556396],
       [ 0.04384034, -0.01403742, -0.00416575, -0.00857059, -0.00630454,
        -0.03281386, -0.01693771,  0.02295699, -0.0383137 ,  0.0062729 ],
       [-0.03078157,  0.01142633,  0.0488565 ,  0.01137779,  0.0174656 ,
         0.04925337,  0.01266989, -0.03594539