In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### One Hot Representation Based on predefined Vocabulary size

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5983, 5438, 7432, 1487],
 [5983, 5438, 7432, 9532],
 [5983, 9914, 7432, 4921],
 [1778, 5361, 2408, 439, 3451],
 [1778, 5361, 2408, 439, 2583],
 [2715, 5983, 2442, 7432, 3182],
 [8524, 2439, 1686, 439]]

## word Embedding Representation

In [8]:


from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

### Sequence Padding as Neural networks expect inputs of a fixed size,

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5983 5438 7432 1487]
 [   0    0    0    0 5983 5438 7432 9532]
 [   0    0    0    0 5983 9914 7432 4921]
 [   0    0    0 1778 5361 2408  439 3451]
 [   0    0    0 1778 5361 2408  439 2583]
 [   0    0    0 2715 5983 2442 7432 3182]
 [   0    0    0    0 8524 2439 1686  439]]


## feature representation

In [11]:

dim=10

### Building the Embedding Layer key parameters:-Vocabulary size , Feature Dimension, Input_Length

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Vector Transformation :-  Transform the padded indices into dense vectors

In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 48ms/step


array([[[-0.01838888,  0.04832238,  0.0407427 , -0.04226818,
          0.01884772,  0.00990888, -0.02346269,  0.04155283,
          0.00534429,  0.04352308],
        [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,
          0.01884772,  0.00990888, -0.02346269,  0.04155283,
          0.00534429,  0.04352308],
        [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,
          0.01884772,  0.00990888, -0.02346269,  0.04155283,
          0.00534429,  0.04352308],
        [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,
          0.01884772,  0.00990888, -0.02346269,  0.04155283,
          0.00534429,  0.04352308],
        [-0.02925104,  0.01240342, -0.03821792, -0.03060368,
          0.04209201, -0.04916923,  0.01337086,  0.03524205,
          0.0290224 ,  0.01381719],
        [ 0.02056816,  0.01757495,  0.0459018 ,  0.02771783,
          0.01813367, -0.02246429, -0.00755682,  0.04223794,
         -0.02432542,  0.02919055],
        [ 0.03178595, -0.03691284,  0.0306932 ,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5983, 5438, 7432, 1487], dtype=int32)

### View the 10-dimensional vector representation of the first sentence

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 21ms/step


array([[-0.01838888,  0.04832238,  0.0407427 , -0.04226818,  0.01884772,
         0.00990888, -0.02346269,  0.04155283,  0.00534429,  0.04352308],
       [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,  0.01884772,
         0.00990888, -0.02346269,  0.04155283,  0.00534429,  0.04352308],
       [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,  0.01884772,
         0.00990888, -0.02346269,  0.04155283,  0.00534429,  0.04352308],
       [-0.01838888,  0.04832238,  0.0407427 , -0.04226818,  0.01884772,
         0.00990888, -0.02346269,  0.04155283,  0.00534429,  0.04352308],
       [-0.02925104,  0.01240342, -0.03821792, -0.03060368,  0.04209201,
        -0.04916923,  0.01337086,  0.03524205,  0.0290224 ,  0.01381719],
       [ 0.02056816,  0.01757495,  0.0459018 ,  0.02771783,  0.01813367,
        -0.02246429, -0.00755682,  0.04223794, -0.02432542,  0.02919055],
       [ 0.03178595, -0.03691284,  0.0306932 ,  0.03872767,  0.00409472,
         0.00636389,  0.01449019, -0.00214174